# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mapreduce.proto',
  package='mapreduce',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmapreduce.proto\x12\tmapreduce\"@\n\nMapRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\t\n\x01M\x18\x03 \x01(\x05\"8\n\rReduceRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\"\x1a\n\nOutputPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"!\n\x0bStopRequest\x12\x12\n\nshouldstop\x18\x01 \x01(\x08\"&\n\x10ShutDownResponse\x12\x12\n\nisshutdown\x18\x01 \x01(\x08\x32\xc2\x01\n\tMapReduce\x12\x37\n\x03Map\x12\x15.mapreduce.MapRequest\x1a\x15.mapreduce.OutputPath\"\x00\x30\x01\x12=\n\x06Reduce\x12\x18.mapreduce.ReduceRequest\x1a\x15.mapreduce.OutputPath\"\x00\x30\x01\x12=\n\x04Stop\x12\x16.mapreduce.StopRequest\x1a\x1b.mapreduce.ShutDownResponse\"\x00\x62\x06proto3'
)




_MAPREQUEST = _descriptor.Descriptor(
  name='MapRequest',
  full_name='mapreduce.MapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_path', full_name='mapreduce.MapRequest.input_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_path', full_name='mapreduce.MapRequest.output_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='M', full_name='mapreduce.MapRequest.M', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=94,
)


_REDUCEREQUEST = _descriptor.Descriptor(
  name='ReduceRequest',
  full_name='mapreduce.ReduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_path', full_name='mapreduce.ReduceRequest.input_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_path', full_name='mapreduce.ReduceRequest.output_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=152,
)


_OUTPUTPATH = _descriptor.Descriptor(
  name='OutputPath',
  full_name='mapreduce.OutputPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='mapreduce.OutputPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=180,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='mapreduce.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shouldstop', full_name='mapreduce.StopRequest.shouldstop', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=215,
)


_SHUTDOWNRESPONSE = _descriptor.Descriptor(
  name='ShutDownResponse',
  full_name='mapreduce.ShutDownResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isshutdown', full_name='mapreduce.ShutDownResponse.isshutdown', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=255,
)

DESCRIPTOR.message_types_by_name['MapRequest'] = _MAPREQUEST
DESCRIPTOR.message_types_by_name['ReduceRequest'] = _REDUCEREQUEST
DESCRIPTOR.message_types_by_name['OutputPath'] = _OUTPUTPATH
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['ShutDownResponse'] = _SHUTDOWNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapRequest = _reflection.GeneratedProtocolMessageType('MapRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPREQUEST,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.MapRequest)
  })
_sym_db.RegisterMessage(MapRequest)

ReduceRequest = _reflection.GeneratedProtocolMessageType('ReduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDUCEREQUEST,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.ReduceRequest)
  })
_sym_db.RegisterMessage(ReduceRequest)

OutputPath = _reflection.GeneratedProtocolMessageType('OutputPath', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTPATH,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.OutputPath)
  })
_sym_db.RegisterMessage(OutputPath)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

ShutDownResponse = _reflection.GeneratedProtocolMessageType('ShutDownResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNRESPONSE,
  '__module__' : 'mapreduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.ShutDownResponse)
  })
_sym_db.RegisterMessage(ShutDownResponse)



_MAPREDUCE = _descriptor.ServiceDescriptor(
  name='MapReduce',
  full_name='mapreduce.MapReduce',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=452,
  methods=[
  _descriptor.MethodDescriptor(
    name='Map',
    full_name='mapreduce.MapReduce.Map',
    index=0,
    containing_service=None,
    input_type=_MAPREQUEST,
    output_type=_OUTPUTPATH,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Reduce',
    full_name='mapreduce.MapReduce.Reduce',
    index=1,
    containing_service=None,
    input_type=_REDUCEREQUEST,
    output_type=_OUTPUTPATH,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='mapreduce.MapReduce.Stop',
    index=2,
    containing_service=None,
    input_type=_STOPREQUEST,
    output_type=_SHUTDOWNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPREDUCE)

DESCRIPTOR.services_by_name['MapReduce'] = _MAPREDUCE

# @@protoc_insertion_point(module_scope)
